### ISSUE TITLE
idea for this project

### ISSUE THREAD

**Issue by thambu1710** [Rahul-Maru/GoL#1]
add undo, redo GUI and save file system with pre-built models to tinker with

**Comment by ivn-13** [comment]
> add undo, redo GUI and save file system with pre-built models to tinker with

Yeah, I agree

**Comment by Rahul-Maru** [comment]
Thanks for the sugggestions!

What do you mean by undo? do you mean reset/clear because those are already there.
The GUI is in the works. Will finish it when I surface from the sea of homework
The third idea is great! I'll implement this in a future version.

I'm also going to:
- further reduce lag
- add a random seed generator
- expand to other cellular automata

**Comment by thambu1710** [comment]
nver mind the undo thing, i get it
